import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/contexts/auth";

const inter = Inter({ subsets: ["latin"] });

/** @type {import("next").Metadata} */
export const metadata = {
  title: "Skill Cave - Learning Management System",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
